### ISSUE TITLE
omero-py install instructions should not pin pyhthon3.6

### ISSUE THREAD

**Issue by glyg** [openmicroscopy/ome-documentation#2213]
Hi!

The current version of the installation instructions for `omero-py` either from conda or pip, instruct the users to use python 3.6 when newer versions of python work just fine. As python 3.6 gets older (I think it is not supported by numpy anymore) I think this should be clarified. 

Here is the file:

https://github.com/ome/omero-documentation/blob/759dcafeec65e31e79920ffcd4742ed34764643f/omero/users/cli/installation.rst

I'm opening a PR with a proposed fix straight away.

**Comment by sbesson** [comment]
:+1: Python 3.6 is actually EOL (https://endoflife.date/python) so updating these instructions makes complete sense from a user perspective. From a sysadmin perspective, we are currently evaluating the instructions/options for upgrading CentOS 7 environments since Python 3.6 remains the version shipped in the default packages - see https://github.com/ome/omero-install/pull/259 and https://github.com/ome/omero-install/pull/260
