### ISSUE TITLE
RHEL9 / Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ghost** [openmicroscopy/ome-documentation#2266]
Hi all,

I wonder if Ubuntu 22.04 LTS (released on 04/21/2022) or RHEL9 (05/17/2022)
is currently supported or planned to be supported by OMERO. Thanks!

**Comment by dominikl** [comment]
Hi,

currently Ubuntu 20.04, Debian 10 and CentOS 7 are officially supported: See [OMERO.server installation](https://omero.readthedocs.io/en/stable/sysadmins/unix/server-installation.html). I'm not aware of plans to support newer releases soon. Personally I installed it on a Ubuntu 22.04 machine using the 20.04 instructions without problems. Redhat is trickier. If I remember correctly you'll run into the problem that Ice 3.6 is not available for newer CentOS versions.

Kind Regards,
Dominik

**Comment by chdietrich** [comment]
Hi Dominik,

Thank you for your reply. I have checked this more closely now. The only problem is the ZeroC Ice library. This is dynamically linked by OME and its dependencies are not fully included in Ubuntu Jammy. So you have to compile this library yourself, which is not easy due to the stricter code checking of the newer GCC version. With questionable disabling code checking, however, it runs.

https://github.com/chdietrich/zeroc-ice-ubuntu2204

Maybe this will help someone reading this issue.

Best regards,
Christian 

PS: ghost = me

**Comment by dominikl** [comment]
👍 Thank you very much Christian!

**Comment by jburel** [comment]
glencoesoftware is building artifacts and wheels 
see https://github.com/glencoesoftware/zeroc-ice-ubuntu2204-x86_64 and https://github.com/glencoesoftware/zeroc-ice-py-ubuntu2204-x86_64
We are planning to use them in our official documentation

**Comment by chdietrich** [comment]
> glencoesoftware is building artifacts and wheels see https://github.com/glencoesoftware/zeroc-ice-ubuntu2204-x86_64 and https://github.com/glencoesoftware/zeroc-ice-py-ubuntu2204-x86_64 We are planning to use them in our official documentation

Interesting, they use the same approach, simply disabling strict code checking. 
I am not sure if this is an acceptable solution or too much tinkering.

> We are planning to use them in our official documentation

Your script is easy to use and doesn't require a github workflow.
If I want to build it manually/by myself I would therefore prefer yours.

**Comment by jburel** [comment]
We are now preparing documentation for both Ubuntu 22.04 and Rocky Linux 9
see https://github.com/ome/omero-documentation/pull/2323

**Comment by jburel** [comment]
Installation instructions have now been added
